### ISSUE TITLE
Question: making a new dataset

### ISSUE THREAD

**Issue by MichinariNukazawa** [nagadomi/lbpcascade_animeface#3]
I am thinking about creating a dataset by myself.
What is the number of images in your data set?
Also, the number of faces in the average image?

Thanks.

related:
https://github.com/nagadomi/animeface-2009/issues/3

**Comment by nagadomi** [comment]
positive and negative dataset each contains around 20000 images.
If you can read Japanese, I have described it in blog post / comment.
http://ultraist.hatenablog.com/entry/20110718/1310965532

**Comment by MichinariNukazawa** [comment]
Thanks!
